%==============================================================
% FileName: VdwGaussian.m
% Description: Get the value of Gauss function in every gauss integral
% point 
% Author: Changhao Li
% Date created: 18 Jul 2017
% Version: 1.00
% Date last revised: 18 Jul 2017
% Revised by: Changhao Li
%==============================================================
function gaussfunc = get_gaussfunc(atom, atom_ele, nele, natom, sigma, gauss_pos, ele_neighbour_gauss)
%==============================================================
% input parameters: 
% ref_atom_pos(natom, 2): referential position of every atom, generated by
%    get_ref_atom_pos.m
% atom_ele(natom, 1): the element number that a atom belongs to
% nele: the number of elements
% natom: the number of atoms
% output parameters:
% gaussfunc(nele, 13):  the value of Gauss function in 12 gauss points,the 13th is total atom number in
% the element
%==============================================================
gaussfunc = zeros(nele, 13);

pos1=0.873821971016996;
pos2=0.063089014491502;
pos11=0.501426509658179;
pos22=0.249286745170910;
pos111=0.636502499121399;
pos222=0.310352451033785;
pos333=0.053145049844816;
gauss_ref_pos = [pos1     pos2;     pos2      pos1;      pos2     pos2; ...
                               pos11   pos22;   pos22    pos11;   pos22    pos22; ...
                               pos111 pos222; pos111 pos333; pos222 pos333; ...
                               pos333 pos222; pos333 pos111; pos333 pos222];
                                                                                               
for i = 1:natom
    ele = atom_ele(i); % the element number that this atom belongs to
    xx = atom(i, 1); % x coordinate of this atom
    yy = atom(i, 2); % y coordinate of this atom
    nei = ele_neighbour_gauss(ele, :); % neighbour element list of this element
    gaussfunc(ele, 13) = gaussfunc(ele, 13) + 1; % calculate the number of atoms in this element
    for nele = 1: nei(1) % for every element in neighbour list
        iele = nei(nele + 1); % neighbour element number
        for ng = 1: 12 
            x = gauss_pos(iele, ng, 1); % x coordinate of this gauss point
            y = gauss_pos(iele, ng, 2);
            if (sqrt((x-xx)^2 + (y-yy)^2) < 3*sigma) % if the distance between gauss point and this atom is less than 3*sigma

                % 2D Gauss function value in every gauss point
                gaussfunc(iele, ng) = gaussfunc(iele, ng) + 1/(2*pi*sigma^2) * exp(-(((x-xx))^2+((y-yy))^2)/(2*sigma^2));
                
            end
        end
    end
end


